import type { GreenRoomTheme } from './tokens'

// ─── Shared shape defaults ───────────────────────────────────────────────────

const shapeRound = {
  radiusCard:  '10px',
  radiusNode:  '6px',
  radiusBadge: '3px',
  radiusBtn:   '5px',
  radiusChip:  '10px',
}

const shapeSquare = {
  radiusCard:  '8px',
  radiusNode:  '4px',
  radiusBadge: '2px',
  radiusBtn:   '4px',
  radiusChip:  '4px',
}

// ─── Shared typography ───────────────────────────────────────────────────────

const typographySystem = {
  fontBase:           'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  fontMono:           'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
  fontSizeXs:         '9px',
  fontSizeSm:         '11px',
  fontSizeMd:         '13px',
  fontSizeLg:         '15px',
  fontWeightNormal:   500,
  fontWeightBold:     700,
  letterSpacingLabel: '0.06em',
}

const typographyEditorial = {
  fontBase:           '"Georgia", "Times New Roman", serif',
  fontMono:           'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
  fontSizeXs:         '9px',
  fontSizeSm:         '11px',
  fontSizeMd:         '13px',
  fontSizeLg:         '15px',
  fontWeightNormal:   500,
  fontWeightBold:     700,
  letterSpacingLabel: '0.08em',
}

// ─── D Light — Midnight Mint (default) ──────────────────────────────────────

export const themeDLight: GreenRoomTheme = {
  id:          'd-light',
  name:        'Midnight Mint',
  description: 'Default · clean white with soft mint green accents',
  color: {
    bgBase:        '#f8fafc',
    bgSurface:     '#ffffff',
    bgElevated:    '#f1f5f9',
    bgHeader:      '#ffffff',
    bgPanel:       '#ffffff',
    bgNodeDefault:  '#ffffff',
    bgNodeSelected: '#f0fdf9',
    bgNodeAffected: '#fef2f2',
    bgNodeDim:      '#f8fafc',
    accent:        '#059669',
    accentHover:   '#047857',
    accentSubtle:  '#d1fae5',
    accent2:       '#818cf8',
    border:        '#e2e8f0',
    borderStrong:  '#cbd5e1',
    borderSel:     '#059669',
    borderAff:     '#dc2626',
    textPrimary:   '#0f172a',
    textSecondary: '#475569',
    textMuted:     '#94a3b8',
    textNode:      '#475569',
    textNodeSel:   '#0f172a',
    textNodeDim:   '#cbd5e1',
    statusOk:      '#059669',
    statusWarn:    '#d97706',
    statusErr:     '#dc2626',
    edgeDep:       '#818cf8',
    edgeCall:      '#059669',
    edgeDim:       '#e2e8f0',
    badgeActiveBg: '#d1fae5', badgeActiveFg: '#059669',
    badgeExpBg:    '#fff7ed', badgeExpFg:    '#ea580c',
    badgeDepBg:    '#f1f5f9', badgeDepFg:    '#94a3b8',
    badgeCritBg:   '#fef2f2', badgeCritFg:   '#dc2626',
    shadow:        'rgba(0,0,0,0.08)',
  },
  typography: typographySystem,
  shape: shapeRound,
}

// ─── D Dark — Midnight Mint dark ────────────────────────────────────────────

export const themeDDark: GreenRoomTheme = {
  id:          'd-dark',
  name:        'Midnight Mint Dark',
  description: 'Deep navy with soft mint green accents',
  color: {
    bgBase:        '#0f172a',
    bgSurface:     '#111827',
    bgElevated:    '#1e293b',
    bgHeader:      '#111827',
    bgPanel:       '#111827',
    bgNodeDefault:  '#111827',
    bgNodeSelected: '#0f2a1f',
    bgNodeAffected: '#1c0a0a',
    bgNodeDim:      '#0a1020',
    accent:        '#34d399',
    accentHover:   '#10b981',
    accentSubtle:  '#065f46',
    accent2:       '#818cf8',
    border:        '#1e293b',
    borderStrong:  '#334155',
    borderSel:     '#34d399',
    borderAff:     '#f87171',
    textPrimary:   '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted:     '#64748b',
    textNode:      '#94a3b8',
    textNodeSel:   '#f8fafc',
    textNodeDim:   '#334155',
    statusOk:      '#34d399',
    statusWarn:    '#fbbf24',
    statusErr:     '#f87171',
    edgeDep:       '#818cf8',
    edgeCall:      '#34d399',
    edgeDim:       '#1e293b',
    badgeActiveBg: '#052e16', badgeActiveFg: '#34d399',
    badgeExpBg:    '#431407', badgeExpFg:    '#fb923c',
    badgeDepBg:    '#1e293b', badgeDepFg:    '#64748b',
    badgeCritBg:   '#450a0a', badgeCritFg:   '#f87171',
    shadow:        'rgba(0,0,0,0.5)',
  },
  typography: typographySystem,
  shape: shapeRound,
}

// ─── C Light — Backstage Warmth light ───────────────────────────────────────

export const themeCLight: GreenRoomTheme = {
  id:          'c-light',
  name:        'Backstage Warmth',
  description: 'Warm parchment with amber and sage accents',
  color: {
    bgBase:        '#faf8f2',
    bgSurface:     '#ffffff',
    bgElevated:    '#f5f1e4',
    bgHeader:      '#f5f1e4',
    bgPanel:       '#f5f1e4',
    bgNodeDefault:  '#ffffff',
    bgNodeSelected: '#fdf8ec',
    bgNodeAffected: '#fde8e4',
    bgNodeDim:      '#f5f1e4',
    accent:        '#5a6e50',
    accentHover:   '#4a5e40',
    accentSubtle:  '#e8f0e4',
    accent2:       '#7060a8',
    border:        '#e0d8c0',
    borderStrong:  '#c8bfa0',
    borderSel:     '#c8962a',
    borderAff:     '#c05040',
    textPrimary:   '#2e2a1e',
    textSecondary: '#5a5040',
    textMuted:     '#9a9080',
    textNode:      '#5a5040',
    textNodeSel:   '#2e2a1e',
    textNodeDim:   '#b0a890',
    statusOk:      '#5a7a50',
    statusWarn:    '#c8962a',
    statusErr:     '#c05040',
    edgeDep:       '#c8962a',
    edgeCall:      '#5a7a50',
    edgeDim:       '#e0d8c0',
    badgeActiveBg: '#e8f0e4', badgeActiveFg: '#4a6040',
    badgeExpBg:    '#fef3cd', badgeExpFg:    '#8a6010',
    badgeDepBg:    '#f0ece0', badgeDepFg:    '#8a8070',
    badgeCritBg:   '#fde8e4', badgeCritFg:   '#b04030',
    shadow:        'rgba(0,0,0,0.07)',
  },
  typography: typographyEditorial,
  shape: shapeSquare,
}

// ─── C Dark — Backstage Warmth dark ─────────────────────────────────────────

export const themeCDark: GreenRoomTheme = {
  id:          'c-dark',
  name:        'Backstage Warmth Dark',
  description: 'Theatrical olive-black with amber gold accents',
  color: {
    bgBase:        '#131108',
    bgSurface:     '#1c1a0f',
    bgElevated:    '#22201a',
    bgHeader:      '#1c1a0f',
    bgPanel:       '#1c1a0f',
    bgNodeDefault:  '#1c1a0f',
    bgNodeSelected: '#22201a',
    bgNodeAffected: '#2d1010',
    bgNodeDim:      '#161410',
    accent:        '#a8c5a0',
    accentHover:   '#c8ddc5',
    accentSubtle:  '#2a3d28',
    accent2:       '#a89cc8',
    border:        '#2a2618',
    borderStrong:  '#3a3626',
    borderSel:     '#d4a853',
    borderAff:     '#e07070',
    textPrimary:   '#f0ede4',
    textSecondary: '#c8c4b8',
    textMuted:     '#7a7060',
    textNode:      '#c8c4b8',
    textNodeSel:   '#f0ede4',
    textNodeDim:   '#5a5040',
    statusOk:      '#84a98c',
    statusWarn:    '#d4a853',
    statusErr:     '#e07070',
    edgeDep:       '#d4a853',
    edgeCall:      '#84a98c',
    edgeDim:       '#2a2618',
    badgeActiveBg: '#1e2e1a', badgeActiveFg: '#84a98c',
    badgeExpBg:    '#2d2010', badgeExpFg:    '#d4a853',
    badgeDepBg:    '#252218', badgeDepFg:    '#6a6050',
    badgeCritBg:   '#2d1010', badgeCritFg:   '#e07070',
    shadow:        'rgba(0,0,0,0.6)',
  },
  typography: typographyEditorial,
  shape: shapeSquare,
}
